[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
  let g:airline_theme='one'
  set background=dark
  colorscheme one
'''
