[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'ujihisa/neco-look'
onJ_source = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''                                     
  let g:deoplete#sources#clang#libclang_path = '/home/kakehi/.pyenv/versions/anaconda3-4.1.1/pkgs/clang-3.9.0-0/lib/libclang.so.3.9'
  let g:deoplete#sources#clang#clang_header = '/home/kakehi/.pyenv/versions/anaconda3-4.1.1/lib/clang'
'''
on_event = 'InsertEnter'
on_ft = ['c','cpp','cmake']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_event = 'InsertEnter'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'
depends = 'deoplete.nvim'
if = "has('nvim')"
on_ft = 'go'
build = 'make'
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gcode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
let g:deoplete#sources#go#use_cache = 1
let g:deoplete#sources#go#json_directory = '~/.cache/deoplete/go/$GOOS_$GOARCH'
''

[[plugins]]
repo = 'nsf/gocode'
on_ft = 'go'

[[plugins]]
repo = 'ujihisa/neco-look'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


#----------------------------------------
# language syntax file
#----------------------------------------

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['js', 'jsx', 'javascript.jsx']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
nmap <silent>j <Plug>(accelerated_jk_gj)
nmap <silent>k <Plug>(accelerated_jk_gk)
'''


